#!/bin/bash
## A SASSIFI script (run_one_injection.py) looks for the following log files to categorize an injection run (Masked, SDC, or Application specific SDC). This sdc_check.sh script should generate the following files:
## diff.log: if the program generates a separate output file (e.g., output.txt), diff the file with the golden output file and store the diff in diff.log.
## stdout_diff.log: diff stdout generated by the program with the golden stdout and store it in stdout_diff.log. Remove the string that matches ":::Injecting.*:::" from the stdout.
## stderr_diff.log: diff stderr generated by the program with the golden stderr and store it in stderr_diff.log.
## special_check.log: if the application specific check fails, the special_check.log should contain some non-empty string.
## if the user prefers to skip one of these checks, he/she should create an empty log file (e.g., touch diff.log). 

# if your program creates an output file (e.g., output.txt) compare it to the file created just now and store the difference in diff.log
# Example: diff output.txt ${APP_DIR}/golden_output.txt > diff.log
touch diff.log 

# comparing stdout generated by your program
#clean stdout.txt by removing the strings that were printed by the SASSIFI error injection handler
cp stdout.txt clean_stdout.txt
sed -i 's/:::value_before.*value_before_end::://g' clean_stdout.txt
sed -i 's/:::value_after.*value_after_end::://g' clean_stdout.txt
sed -i 's/:::Injecting.*::://g' clean_stdout.txt
diff clean_stdout.txt ${APP_DIR}/golden_stdout.txt > stdout_diff.log
rm clean_stdout.txt

# comparing stderr generated by your program
diff stderr.txt ${APP_DIR}/golden_stderr.txt > stderr_diff.log

# Application specific output: The following check will be performed only if at least one of diff.log, stdout_diff.log, and stderr_diff.log is different
grep sum stdout.txt > selected_output.txt 
grep sum ${APP_DIR}/golden_stdout.txt > selected_golden_output.txt 
diff selected_output.txt selected_golden_output.txt > special_check.log
